---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-bgp
  failurePolicy: Fail
  name: bgp-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bgp
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-bgppeer
  failurePolicy: Fail
  name: bgppeer-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bgppeers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-interface
  failurePolicy: Fail
  name: interface-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - interfaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-prefixset
  failurePolicy: Fail
  name: prefixset-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - prefixsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-vrf
  failurePolicy: Fail
  name: vrf-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrfs
  sideEffects: None
