{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: network-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists
  - banners
  - bgp
  - bgppeers
  - certificates
  - devices
  - dns
  - evpninstances
  - interfaces
  - isis
  - managementaccesses
  - networkvirtualizationedges
  - ntp
  - ospf
  - pim
  - prefixsets
  - routingpolicies
  - snmp
  - syslogs
  - users
  - vlans
  - vrfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists/finalizers
  - banners/finalizers
  - bgp/finalizers
  - bgppeers/finalizers
  - certificates/finalizers
  - devices/finalizers
  - dns/finalizers
  - evpninstances/finalizers
  - interfaces/finalizers
  - isis/finalizers
  - managementaccesses/finalizers
  - networkvirtualizationedges/finalizers
  - ntp/finalizers
  - ospf/finalizers
  - pim/finalizers
  - prefixsets/finalizers
  - routingpolicies/finalizers
  - snmp/finalizers
  - syslogs/finalizers
  - users/finalizers
  - vlans/finalizers
  - vrfs/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists/status
  - banners/status
  - bgp/status
  - bgppeers/status
  - certificates/status
  - devices/status
  - dns/status
  - evpninstances/status
  - interfaces/status
  - isis/status
  - managementaccesses/status
  - networkvirtualizationedges/status
  - ntp/status
  - ospf/status
  - pim/status
  - prefixsets/status
  - routingpolicies/status
  - snmp/status
  - syslogs/status
  - users/status
  - vlans/status
  - vrfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nx.cisco.networking.metal.ironcore.dev
  resources:
  - bordergateways
  - systems
  - vpcdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nx.cisco.networking.metal.ironcore.dev
  resources:
  - bordergateways/finalizers
  - systems/finalizers
  - vpcdomains/finalizers
  verbs:
  - update
- apiGroups:
  - nx.cisco.networking.metal.ironcore.dev
  resources:
  - bordergateways/status
  - systems/status
  - vpcdomains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nx.cisco.networking.metal.ironcore.dev
  resources:
  - managementaccessconfigs
  - networkvirtualizationedgeconfigs
  verbs:
  - get
  - list
  - watch
{{- end -}}
