{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: network-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists
  - banners
  - bgp
  - bgppeers
  - certificates
  - devices
  - dns
  - interfaces
  - isis
  - managementaccesses
  - ntp
  - pim
  - snmp
  - syslogs
  - users
  - vrfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists/finalizers
  - banners/finalizers
  - bgp/finalizers
  - bgppeers/finalizers
  - certificates/finalizers
  - devices/finalizers
  - dns/finalizers
  - interfaces/finalizers
  - isis/finalizers
  - managementaccesses/finalizers
  - ntp/finalizers
  - pim/finalizers
  - snmp/finalizers
  - syslogs/finalizers
  - users/finalizers
  - vrfs/finalizers
  verbs:
  - update
- apiGroups:
  - networking.metal.ironcore.dev
  resources:
  - accesscontrollists/status
  - banners/status
  - bgp/status
  - bgppeers/status
  - certificates/status
  - devices/status
  - dns/status
  - interfaces/status
  - isis/status
  - managementaccesses/status
  - ntp/status
  - pim/status
  - snmp/status
  - syslogs/status
  - users/status
  - vrfs/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
