## Append samples of your project ##
resources:
- v1alpha1_device.yaml
- v1alpha1_interface.yaml
- v1alpha1_banner.yaml
- v1alpha1_user.yaml
- v1alpha1_dns.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
