## Append samples of your project ##
resources:
- v1alpha1_device.yaml
- v1alpha1_interface.yaml
- v1alpha1_banner.yaml
- v1alpha1_user.yaml
- v1alpha1_dns.yaml
- v1alpha1_ntp.yaml
- v1alpha1_acl.yaml
- v1alpha1_certificate.yaml
- v1alpha1_snmp.yaml
- v1alpha1_syslog.yaml
- v1alpha1_managementaccess.yaml
- v1alpha1_isis.yaml
- v1alpha1_vrf.yaml
- v1alpha1_pim.yaml
- v1alpha1_bgp.yaml
- v1alpha1_bgppeer.yaml
- v1alpha1_ospf.yaml
- v1alpha1_vlan.yaml
- v1alpha1_evi.yaml
- v1alpha1_nve.yaml
- v1alpha1_prefixset.yaml
- v1alpha1_routingpolicy.yaml
- cisco/nx/v1alpha1_bordergateway.yaml
- cisco/nx/v1alpha1_managementaccessconfig.yaml
- cisco/nx/v1alpha1_nveconfig.yaml
- cisco/nx/v1alpha1_system.yaml
- cisco/nx/v1alpha1_vpcdomain.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
