## Append samples of your project ##
resources:
- v1alpha1_device.yaml
- v1alpha1_interface.yaml
- v1alpha1_banner.yaml
- v1alpha1_user.yaml
- v1alpha1_dns.yaml
- v1alpha1_ntp.yaml
- v1alpha1_acl.yaml
- v1alpha1_certificate.yaml
- v1alpha1_snmp.yaml
- v1alpha1_syslog.yaml
- v1alpha1_managementaccess.yaml
- v1alpha1_isis.yaml
- v1alpha1_vrf.yaml
- v1alpha1_pim.yaml
- v1alpha1_bgp.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
