apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: ISIS
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.metal.ironcore.dev/device-name: leaf1
  name: underlay
spec:
  deviceRef:
    name: leaf1
  instance: UNDERLAY
  networkEntityTitle: 49.0001.0000.0000.0010.00
  type: Level1
  overloadBit: OnStartup
  addressFamilies:
    - IPv4Unicast
    - IPv6Unicast
  interfaces:
    - name: eth1-1
    - name: eth1-2
    - name: lo0
    - name: lo1
