apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: DNS
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.metal.ironcore.dev/device-name: leaf1
  name: dns
spec:
  deviceRef:
    name: leaf1
  domain: net.cloud.sap
  servers:
    - address: 8.8.8.8
      vrfName: management
  sourceInterfaceName: mgmt0
