apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.metal.ironcore.dev/device-name: leaf1
  name: user
spec:
  deviceRef:
    name: leaf1
  username: testuser
  password:
    secretKeyRef:
      name: user-password
      key: password
  roles:
    - name: network-admin
    - name: network-operator
  sshPublicKey:
    secretKeyRef:
      name: user-ssh-key
      key: ssh-publickey
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-password
type: Opaque
stringData:
  password: user123
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-ssh-key
type: Opaque
data:
  ssh-publickey: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFERWdzQUtabi9oeFBNS3lmd0tib2lPRWV1TDliVHFXNzlRZkVROGgwa3BHaGtGSkpFV1IxZTNCdlhwZFQ5S1lRT2FLUW5OdzMyYXRVTHdlU1FRTkdoNlM3M0Z2RUl3WVZpdU5DbXlnRHhwaWFKTElpWUhBZnMzTlE4d0dHNzBsK0RLNnZQaGtjTzZ1dnEyWFJQK3kxVzlnTUFLbGdNUGo1QkNsMkxSNkhVTzkvSnp2aTF5Ulg0dzRFNXNocHZjVm9VVUI4dWJGSjBJeWZNVFhiL3NRckZ2anE0dWtIM3dBVjRDTXJzUDZmajVGb0FRekp3M2psSzVHQ3RLOEZxa1VrUk9CZXh3V0diRkZqU2JveDVLWFQycWx1ZExvY3lRdHcxMHJCNkcvM2FmNDB0UUpMSGQwdTZMbmFDZ0hHZlBvZDNaOXUyYUw2RFIxazVoQnRHWEdXeFogSXJvbkNvcmUgVGVzdA==
