apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnmi-test-server
  namespace: default
  labels:
    app.kubernetes.io/name: gnmi-test-server
    app.kubernetes.io/instance: gnmi-test-server
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: test-server
    app.kubernetes.io/part-of: network-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gnmi-test-server
      app.kubernetes.io/instance: gnmi-test-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gnmi-test-server
        app.kubernetes.io/instance: gnmi-test-server
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: test-server
        app.kubernetes.io/part-of: network-operator
        app.kubernetes.io/managed-by: kustomize
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gnmi-test-server
        image: ghcr.io/ironcore-dev/gnmi-test-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9339
          name: grpc
          protocol: TCP
        - containerPort: 8000
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gnmi-test-server
  namespace: default
  labels:
    app.kubernetes.io/name: gnmi-test-server
    app.kubernetes.io/instance: gnmi-test-server
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: test-server
    app.kubernetes.io/part-of: network-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: gnmi-test-server
    app.kubernetes.io/instance: gnmi-test-server
  ports:
  - name: grpc
    port: 9339
    targetPort: 9339
    protocol: TCP
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
