- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - --leader-elect=false
    - --health-probe-bind-address=:8081
    - --provider=openconfig
    - --requeue-interval=15s
    - --max-concurrent-reconciles=5
