# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/networking.metal.ironcore.dev_devices.yaml
- bases/networking.metal.ironcore.dev_interfaces.yaml
- bases/networking.metal.ironcore.dev_banners.yaml
- bases/networking.metal.ironcore.dev_users.yaml
- bases/networking.metal.ironcore.dev_dns.yaml
- bases/networking.metal.ironcore.dev_ntp.yaml
- bases/networking.metal.ironcore.dev_accesscontrollists.yaml
- bases/networking.metal.ironcore.dev_certificates.yaml
- bases/networking.metal.ironcore.dev_snmp.yaml
- bases/networking.metal.ironcore.dev_syslogs.yaml
- bases/networking.metal.ironcore.dev_managementaccesses.yaml
- bases/networking.metal.ironcore.dev_isis.yaml
- bases/networking.metal.ironcore.dev_vrfs.yaml
- bases/networking.metal.ironcore.dev_pim.yaml
- bases/networking.metal.ironcore.dev_bgp.yaml
- bases/networking.metal.ironcore.dev_bgppeers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
